# Generated by Django 6.0.7 on 2026-08-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('column_id', models.AutoField(primary_key=True, serialize=False)),
                ('column_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'column_',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Has',
            fields=[
                ('pk', models.CompositePrimaryKey('project_id', 'column_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('column_id', models.IntegerField()),
                ('has_order', models.IntegerField()),
            ],
            options={
                'db_table': 'has_',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=50)),
                ('project_description', models.CharField(blank=True, max_length=200, null=True)),
                ('project_creation_date', models.DateField()),
            ],
            options={
                'db_table': 'project',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=50, unique=True)),
                ('tag_color', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'tag',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tagged',
            fields=[
                ('pk', models.CompositePrimaryKey('task_id', 'tag_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tagged',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=50)),
                ('task_description', models.CharField(max_length=200)),
                ('task_dead_line', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'task',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_email', models.CharField(max_length=50, unique=True)),
                ('user_password', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user_',
                'managed': False,
            },
        ),
    ]
